version: "3.9"
services:
  lablr:
    build:
      context: .
      dockerfile: Dockerfile
    image: cgundlach13/lablr:latest
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ${HOME}/.lablr
        target: /home/root/.lablr